# Scalars
scalar Date
scalar JSON

# Boilerplate
type Info {
  id: ID!
  name: String!
  description: String
}

# Unkown
# Idle
# Starting
# Running
# Stopped
# Ended
# Error
type StatusCode {
  id: ID!
}

# Training
# Performing
type Mode {
  id: ID!
}

input BotInput {
  type: String
  url: String
  token: String
  features: [Float!]
}

type Bot {
  type: String
  url: String
  token: String
  features: [Float!]
}

input ConfigInput {
  environment: ID!
  mode: ID!
  bots: [BotInput!]!
}

type Config {
  environment: Environment!
  mode: Mode!
  bots: [Bot!]!
}

type Environment {
  id: ID!
  name: String
  observationSpace: FeatureSpace
  actionSpace: FeatureSpace
  rewardSpace: FeatureSpace
}

type Dimension {
  id: ID!
  isContinuous: Boolean
  rangeMin: Float
  rangeMax: Float
}

type FeatureSpace {
  id: ID!
  name: String
  dimensions: [Dimension]
}

type Status {
  id: ID!
  code: StatusCode!
  errors: [String!]!
}

type Observation {
  step: Int!
  data: [Float!]!
  rewards: [Float!]!
  status: Status!
}

type Query {
  listEnvironments: [Environment!]!
  configuration: Config!
  status: Status!
  observe: Observation!
}

type Mutation {
  run(config: ConfigInput!): Status!
  stop: Status!
}
